[project]
name = "expense-tracker-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Siddhesh1420", email = "siddheshdiptil@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "aiosqlite>=0.22.1",
    "fastmcp>=4.0.2",
]

[project.scripts]
expense-tracker-mcp-server = "expense_tracker_mcp_server:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
